### ISSUE TITLE
pip install not finding package

### ISSUE THREAD

**Issue by msmorey** [alertedsnake/packagetracker#2]
Hey all! Thank you so much for developing this. When I run pip install packagetracker I get 

`Collecting packagetracker
  Could not find a version that satisfies the requirement packagetracker (from versions: )
No matching distribution found for packagetracker`

If that's just me, please just send me on my way. Thanks again for all your work.

**Comment by alertedsnake** [comment]
This isn't an issue.  The package is not published into the public [Python Package Index](https://pypi.org/).

**Comment by alertedsnake** [comment]
However, I did just update the README to make that clear.  I copied the readme from the package I forked this from, I guess I forgot to update that.  Thanks for pointing it out!

I did consider publishing it, but so much doesn't really work reliably (mostly due to poor documentation on the service's part) that I don't think that would be the best idea.

**Comment by msmorey** [comment]
That makes complete sense. Thanks for the update; I'll work on installing it from here. Again, this package looks awesome. I wish the carriers had better documentation. Maybe someday soon they'll get their shit together.

**Comment by alertedsnake** [comment]
Or someone (possibly me) will get ambitious enough to actually work out the details by hand.  I've been using this as-is for a while now, and it seems pretty good so far, I just don't want to give people the idea that it's really "done" :)

**Comment by msmorey** [comment]
I hear that man. Thanks for the work. I'm pretty new to coding in general, but if I find anything I can tweak and make better, I'll be sure to pass along what I find.
